unique_ids:
  assets:
    loading-spinner.svg: J5U6UONLNUCLWEVY2AXYPUUO6TFROVVH
  forms:
    client_code: '167813569041761837667342.62663'
  modules:
    client_code.backup: LY7QFFBKFVFWIWVSPZSH5V52EYHBDWWQ
  scripts: {}
  server_modules:
    server_code: '1726314680291920848997499.0928'
